### ISSUE TITLE
lua syntax error on generation

### ISSUE THREAD

**Issue by Coderdreams** [memsharded/conan-premake#1]
Hi. When using this conanfile.txt:

```
[requires]
Poco/1.7.3@lasote/stable
PremakeGen@0.1@memsharded/testing

[generators]
Premake

[options]
Poco:shared=True
OpenSSL:shared=True

[imports]
bin, *.so -> ./bin # Copies all dll files from the package "bin" folder to my project "bin" folder

```

conan install works fine, but when I try to execute:

premake5 gmake

it throws error:

Error: /home/user/project/premake4.lua:3: error loading module 'conanpremake' from file './conanpremake.lua':
    /home/user/project/conanpremake.lua:57: '=' expected near '-'

The problem are this lines:

conan_includedirs_electric-fence = {"/home/user/.conan/data/electric-fence/2.2.0/lasote/stable/package/21ace02f4960dd0c1d50bd3abe1537054de08157/include"}
conan_libdirs_electric-fence = {"/home/user/.conan/data/electric-fence/2.2.0/lasote/stable/package/21ace02f4960dd0c1d50bd3abe1537054de08157/lib"}
...

It seems that lua doesn't like variable identifiers like that.

**Comment by memsharded** [comment]
It seems that you are using premake5, while the generator (and your project premake4.lua?) are premake4 scripts? Could that be the problem? From the docs it says that it is for premake4: http://docs.conan.io/en/latest/integrations/premake.html 
But it is true that from the package recipe it is not clear at all, maybe it could improve, at least with some comments.

Are you forced to used premake5? Maybe we can try to setup a generator for it, shouldn't be difficult starting from the premake4 existing one.

**Comment by Coderdreams** [comment]
I used premake4 too, and the same problem arises. I was just trying premake5 in case it would fix the error but it doesn't, it just seem Lua doesn't like that kind of identifier.

**Comment by memsharded** [comment]
Thanks for telling. I have checked locally and doesn't get that error (but another linker one). I will have a deeper look asap.

**Comment by Coderdreams** [comment]
Thank you, let me know if I can help you in any way.
This is Ubuntu 16.04 64bit version.

I used conan install --build=missing.

**Comment by memsharded** [comment]
I have checked with the conanfile.txt you provided, depending on Poco, and it works mostly fine. It has some linking errors:

``` bash
Linking MyApplication
c:/mingw/bin/../lib/gcc/mingw32/4.9.3/../../../../mingw32/bin/ld.exe: cannot find -lcrypt32.lib
c:/mingw/bin/../lib/gcc/mingw32/4.9.3/../../../../mingw32/bin/ld.exe: cannot find -lmsi.lib
collect2.exe: error: ld returned 1 exit status
MyApplication.make:85: recipe for target 'MyApplication.exe' failed
```

but this is basically because of the deps not compatible in windows for mingw builds. No lua syntax error problem. Now I will check in Ubuntu 16.

**Comment by memsharded** [comment]
Ok, I know what is happening. OpenSSL (transitive dep of Poco), has a dependency to electric-fence in linux, which is an invalid variable name in premake. I have submitted a fix to the Premake generator, so you should be able to try it: https://www.conan.io/source/PremakeGen/0.1/memsharded/testing

Remember to remove the old Premake generator:

``` bash
$ conan remove Premake*
```

You might try also to run `conan install -u` to update it.

However, I have add some issues with the Poco conanfile.txt you provided, trying also in Ubuntu 16, at runtime, not finding the .so files. Your import seems wrong (moreover, it shouldn`t be necessary in linux. Moreover, the .so files are in the lib folder of the package, so in any case, it should be more like

```
lib, *.so* -> ./bin
```

I will try to have a look to these linking issues tomorrow, please tell me if the generator works now. Thank you!

**Comment by Coderdreams** [comment]
Awesome! I just tested it and it works! Also thanks for pointing me out on that issue with the .so files, I couldn't solve that mistery. The thing was that after linking dynamically to those files I couldn't run the program, I got:

./myApp: error while loading shared libraries: libPocoUtil.so.43: 

Now, I point my LD_LIBRARY_PATH to the bin folder and it works. Am I missing some easier way of achieving this? 

Thanks very much for your support.

**Comment by memsharded** [comment]
Great! Yes, of course the way in linux to specify the shared libraries location is setting the LD_LIBRARY_PATH (to the lib subfolder, in this case). Now (from conan 0.11) there is the concepts of virtualenvs that could be used to automatically set and unset this path, but so far the virtualenvs are not doing this automatically. I think I'll suggest this feature in the conan issues. Thanks very much to you for reporting this issue. I think it can be closed now, but please re-open or create a new one if necessary. Cheers
